type TokenName = string

export const bannedTokenNames: TokenName[] = [
  'BigDickTatesOutOfMatrix',
  'BigDicksTrump2024HarambeMusk',
  'function(0x){Marki}',
  'ROLLUX',
  'PUMP',
  'DANTE',
  'SysCat',
  'SKIBIDI TOILET',
  'TEST',
  'Pepe Fomo',
  'Fish Token',
  'TEST',
  'SYSPEPE',
  'Sherpa',
  'SKIBIDI TOILET',
  'Tem Token',
  'Test',
  'Pegasys Farm Deposit Test Token',
  'test',
  'YEET COIN',
  'BigDicksTrump2024SongokuMusk',
  'AZT',
  'Pablete Token',
  'Pegasys Farm Test Token',
]
